name: learn-github-actions
run-name: Deploy to github pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v4
        - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
          with:
            ruby-version: '2.3.8'
        - run: bundle install
        - run: bundle exec jekyll build
        - name: rsync deployments
          uses: burnett01/rsync-deployments@7.0.1
          with:
            switches: -avzr --delete
            path: _site/
            remote_path: /var/www/vhosts/fieldtracks.org/httpdocs
            remote_host: fieldtracks.org
            remote_user: fieldtracks
            remote_key: ${{ secrets.DEPLOY_KEY }}
